# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GiaIEisOINfudpucmuQNdcqaxlnj7Xa
"""

from transformers import GPT2LMHeadModel, GPT2Tokenizer, Trainer, TrainingArguments
from transformers import DataCollatorForLanguageModeling
import torch
from google.colab import files
import os

files.upload()

# Load tokenizer and model
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")

# IMPORTANT FIX (GPT-2 has no pad token)
tokenizer.pad_token = tokenizer.eos_token

model = GPT2LMHeadModel.from_pretrained("gpt2")

# Load dataset
def load_dataset(file_path, tokenizer):
  with open(file_path, "r") as f:
        lines = f.readlines()

  encodings = tokenizer(lines, truncation=True, padding=True, return_tensors="pt")

  class CustomDataset(torch.utils.data.Dataset):
      def __init__(self, encodings):
          self.encodings = encodings

      def __getitem__(self, idx):
          return {
              "input_ids": self.encodings["input_ids"][idx],
              "attention_mask": self.encodings["attention_mask"][idx],
              "labels": self.encodings["input_ids"][idx],
          }

      def __len__(self):
          return len(self.encodings["input_ids"])

  return CustomDataset(encodings)

dataset = load_dataset("dataset.txt.txt", tokenizer)

# Data collator
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# Training arguments
training_args = TrainingArguments(
    output_dir="./gpt2-finetuned",
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_steps=200,
    save_total_limit=2,
    logging_steps=50
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    data_collator=data_collator
)

# Train
trainer.train()

# Save model
output_dir = "./gpt2-finetuned"
os.makedirs(output_dir, exist_ok=True)
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

from transformers import GPT2LMHeadModel, GPT2Tokenizer

model = GPT2LMHeadModel.from_pretrained("gpt2-finetuned", local_files_only=True)
tokenizer = GPT2Tokenizer.from_pretrained("gpt2-finetuned", local_files_only=True)

prompt = "robotics"

input_ids = tokenizer.encode(prompt, return_tensors="pt")

output = model.generate(
    input_ids,
    max_length=100,
    temperature=0.7,
    do_sample=True
)

print(tokenizer.decode(output[0], skip_special_tokens=True))

import os

output_dir = './gpt2-finetuned'

if os.path.exists(output_dir):
    print(f"Directory '{output_dir}' exists.")
    print("Contents:")
    for item in os.listdir(output_dir):
        print(f"- {item}")
else:
    print(f"Directory '{output_dir}' does NOT exist.")